name: Run Artillery with Playwright

on:
  workflow_dispatch:

jobs:
  run-artillery:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the workflow has write permissions to the repository

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g artillery
        npm install -g playwright
        npm install @playwright/test
        npm install gh-pages --save-dev

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Artillery scripts
      run: |
        mkdir -p reports
        for file in *.yml; do
          test_name=$(basename "$file" .yml)
          timestamp=$(date +"%Y/%m/%d/%H-%M-%S")
          mkdir -p "reports/${test_name}/${timestamp}"
          artillery run "$file" -o "reports/${test_name}/${timestamp}/report.json"
          artillery report --output "reports/${test_name}/${timestamp}/report.html" "reports/${test_name}/${timestamp}/report.json"
        done
      env:
        CI: true

    - name: Checkout gh-pages branch
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages

    - name: Copy new reports to gh-pages branch
      run: |
        cp -r reports/* .

    - name: Commit and push reports to gh-pages branch
      run: |
        git add .
        git commit -m "Add Artillery test reports"
        git pull --rebase origin gh-pages
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
