name: Artillery Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-artillery-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # or specify the version of Node.js you need

      - name: Install dependencies
        run: npm install -g artillery

      - name: Create reports directory
        run: mkdir -p reports

      - name: Find Artillery test files
        id: find-files
        run: |
          echo "::set-output name=files::$(find tests -name '*.yml' -print0 | tr '\0' ' ')"

      - name: Run Artillery tests
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          DAY=$(date +%d)
          TIME=$(date +%H%M%S)
          BASE_DIR=reports/$YEAR/$MONTH/$DAY/$TIME
          mkdir -p $BASE_DIR
          for file in ${{ steps.find-files.outputs.files }}; do
            base_name=$(basename $file .yml)
            test_dir=$BASE_DIR/$base_name
            mkdir -p $test_dir
            echo "Running test: $file"
            artillery run $file -o $test_dir/${base_name}.json
            artillery report --output $test_dir/${base_name}.html $test_dir/${base_name}.json
          done
          echo "::set-output name=report_dir::$BASE_DIR"

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Checkout gh-pages branch
        run: |
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Copy reports to gh-pages branch
        run: cp -r reports/* .

      - name: Commit and push reports
        run: |
          git add .
          git commit -m "Deploy Artillery reports for run ${{ github.run_id }}"
          git push -u origin gh-pages

      - name: Clean up
        run: |
          git checkout main
          git branch -D gh-pages
